### ISSUE TITLE
This is not an issue, just a question.

### ISSUE THREAD

**Issue by WalmartMf** [TangyKiwi/KiwiClient#11]
is this only and will be 1.19? because i cant seem to find the version for 1.18. if there is no 1.18 will you make it for that version? if not ty for reading this and have a nice day :) also, q u a c c k hehe

**Comment by TangyKiwi** [comment]
There's a 1.18 (1.18.1) branch but the most up to date is always the latest version. Just use the latest version with [viafabric](https://www.curseforge.com/minecraft/mc-mods/viafabric) or [multiconnect ](https://www.curseforge.com/minecraft/mc-mods/multiconnect)to join backwards.
