### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by WalmartMf** [TangyKiwi/KiwiClient#12]
not sure why but everytime i add my mods with the kiwi mod and launch. it just stucks you on the loading screen. When the bar fills up it reset idk why. all of my mods have the same version and its latest, idk whats causing the crash. here is the list of my mods
![image](https://user-images.githubusercontent.com/99536195/184343260-34c8632f-3b36-4d7d-b8e5-04922ae069c6.png)
![image](https://user-images.githubusercontent.com/99536195/184343321-bd3bdb88-72ed-43fd-9e2f-6000205095db.png)

**Comment by TangyKiwi** [comment]
You have way too many mods for me to accurately tell you what is causing the problem but my best bet is DarkLoadingScreen causing the issue. Try removing that. Otherwise I would recommend starting with a clean install and then testing.

**Comment by TangyKiwi** [comment]
It would also be useful to post your latest.log file, you can add me on discord TaпgуКїщї#6460 for easier communication.

**Comment by TangyKiwi** [comment]
Closed since no response.
