### ISSUE TITLE
ESP incompatible with Iris / Sodium

### ISSUE THREAD

**Issue by TangyKiwi** [TangyKiwi/KiwiClient#6]
ESP "shader" mode will not render with Iris. Could be a compatibility issue with Iris or Sodium, more testing needed.

**Comment by outlineutils** [comment]
issue with sodium probably, my esp is incompatible with sodium for the same reason
probably easier to just add csgo and box modes than actually fix the problem

**Comment by TangyKiwi** [comment]
Incompatible with Iris shaders, Sodium works fine, closing for now
